spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    show_sql: true
    url: jdbc:postgresql://localhost:5431/postgres?currentSchema=nechto
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
logging:
  level:
    org:
      springframework:
        security: debug
liquibase:
  default-schema: nechto
#  data-locations: classpath:db/data.sql
#  schema-locations: classpath:db/changelog/schema.sql
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml
  clearCheckSums: true